### ISSUE TITLE
[bug] Cannot find ID conflicts within the same file!

### ISSUE THREAD

**Issue by ornithologistnightmare** [SS111/Minecraft-ID-Resolver#6]
I was trying to get Resonant Induction to work earlier (the mod registers most of its blocks blocks in the Postinitialisation phase so another mod called CodeChickenCore cannot report any ID conflicts - at least that's what it says), and it kept on crashing due to ID conflicts between two blocks from RI. I ran the ID Resolver on the one configuration file and it said that there were no conflicts - even though Minecraft had already crashed. It would be great if you could fix this.

**Comment by SS111** [comment]
I'm still working on MultiMC integration, I promise!
In the mean time, enjoy the commit thats about to fix your issue.

**Comment by ornithologistnightmare** [comment]
Thanks. That'll solve my problem!
